import {
  Bell,
  BookOpen,
  Building2,
  CalendarDays,
  CreditCard,
  GraduationCap,
  LayoutDashboard,
  Library,
  Settings,
  SquareUser,
  Users,
  ClipboardCheck,
  FileBarChart2,
  Clock3,
} from "lucide-react";

export const sidebarLinks = [
  { href: "/dashboard", label: "Overview", icon: LayoutDashboard },
  { href: "/dashboard/students", label: "Students", icon: Users },
  { href: "/dashboard/faculty", label: "Faculty", icon: GraduationCap },
  { href: "/dashboard/departments", label: "Departments", icon: Building2 },
  { href: "/dashboard/courses", label: "Courses", icon: BookOpen },
  { href: "/dashboard/admissions", label: "Admissions", icon: ClipboardCheck },
  { href: "/dashboard/notices", label: "Notices", icon: Bell },
  { href: "/dashboard/events", label: "Events", icon: CalendarDays },
  { href: "/dashboard/attendance", label: "Attendance", icon: Clock3 },
  { href: "/dashboard/results", label: "Results", icon: FileBarChart2 },
  { href: "/dashboard/fees", label: "Fees", icon: CreditCard },
  { href: "/dashboard/library", label: "Library", icon: Library },
  { href: "/dashboard/settings", label: "Settings", icon: Settings },
  { href: "/dashboard/profile", label: "Profile", icon: SquareUser },
];