import {
  LayoutDashboard,
  Users,
  GraduationCap,
  Building2,
  BookOpen,
  ClipboardCheck,
  Bell,
  CalendarDays,
  BarChart3,
  CreditCard,
  Library,
  Clock3,
  Settings,
  UserCircle2,
} from "lucide-react";

export const sidebarLinks = [
  { label: "Overview", href: "/dashboard", icon: LayoutDashboard },
  { label: "Students", href: "/dashboard/students", icon: Users },
  { label: "Faculty", href: "/dashboard/faculty", icon: GraduationCap },
  { label: "Departments", href: "/dashboard/departments", icon: Building2 },
  { label: "Courses", href: "/dashboard/courses", icon: BookOpen },
  { label: "Admissions", href: "/dashboard/admissions", icon: ClipboardCheck },
  { label: "Notices", href: "/dashboard/notices", icon: Bell },
  { label: "Events", href: "/dashboard/events", icon: CalendarDays },
  { label: "Attendance", href: "/dashboard/attendance", icon: BarChart3 },
  { label: "Results", href: "/dashboard/results", icon: BarChart3 },
  { label: "Fees", href: "/dashboard/fees", icon: CreditCard },
  { label: "Library", href: "/dashboard/library", icon: Library },
  { label: "Timetable", href: "/dashboard/timetable", icon: Clock3 },
  { label: "Settings", href: "/dashboard/settings", icon: Settings },
  { label: "Profile", href: "/dashboard/profile", icon: UserCircle2 },
];